# Generated by Django 5.1.6 on 2025-04-19 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('leased', 'Leased')], default='available', max_length=20)),
                ('region', models.CharField(blank=True, choices=[('central_grounds', 'Central Grounds'), ('north_grounds', 'North Grounds'), ('rugby_corridor', 'Rugby Road Corridor'), ('university_corner', 'West Main / University Corner'), ('jpa', 'Jefferson Park Avenue'), ('downtown_mall', 'Downtown Mall / City Center'), ('barracks_road', 'Barracks Road Area'), ('frys_spring', "Fry's Spring"), ('greenbrier', 'Greenbrier / Barracks West'), ('pantops', 'Pantops & Meadow Creek'), ('shadwell', 'Shadwell & Ivy')], max_length=30)),
                ('proximity', models.CharField(blank=True, choices=[('on_grounds', 'On-Grounds Housing'), ('within_0_5_mi', 'Within 0.5 mi of Grounds'), ('0_5_to_1_mi', '0.5-1 mi from Grounds'), ('1_to_2_mi', '1-2 mi from Grounds'), ('charlottesville', 'Charlottesville City'), ('albemarle', 'Albemarle County')], max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('private_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_properties', to='listing_service.collection')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing_service.collection')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing_service.property')),
            ],
            options={
                'unique_together': {('collection', 'property')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='properties',
            field=models.ManyToManyField(through='listing_service.CollectionProperty', to='listing_service.property'),
        ),
        migrations.CreateModel(
            name='CollectionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='listing_service.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collection', 'user')},
            },
        ),
    ]
