name: Django Migrations
on:
  push:
    branches: [ main, dev, fix-routes, fix-actions, implement-styles ]
  pull_request:
    branches:
      - main
      - dev
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        env:
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_SECRET_KEY: ${{ secrets.GOOGLE_SECRET_KEY }}
            WALKSCORE_API_KEY: ${{ secrets.WALKSCORE_API_KEY }}
        run: |
          python manage.py makemigrations user_service
          python manage.py migrate user_service
          python manage.py makemigrations listing_service
          python manage.py migrate listing_service
          python manage.py makemigrations
          python manage.py migrate